modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="tscerberus"
version="0.1a"

displayName="Cerberus"

authors="TsarHydrantine"

description='''

Funny lava doggo

'''

[[dependencies.tscerberus]]
    # the modid of the dependency
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    
    ordering="NONE"
    side="BOTH"
    
[[dependencies.tscerberus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    
    ordering="NONE"
    side="BOTH"
